import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { basename, join, resolve } from "node:path";

import type { AgentProvider } from "./agent-provider.js";
import { configuredAgents, type LfiConfig } from "./config.js";
import { requireCommand, runCommand } from "./process.js";
import { LFI_VERSION } from "./version.js";

export const WORKER_DOCKERFILE = "Dockerfile.lfi";

const labels = {
  dockerfile: "dev.lfi.dockerfile",
  version: "dev.lfi.version",
  uid: "dev.lfi.uid",
  gid: "dev.lfi.gid",
} as const;

export interface WorkerIdentity {
  uid: number;
  gid: number;
}

export type WorkerImageFreshness =
  | { status: "fresh" }
  | { status: "missing" }
  | {
      status: "stale";
      reasons: ("dockerfile" | "version" | "identity")[];
    };

const digest = (source: string): string =>
  createHash("sha256").update(source).digest("hex");

export const deriveWorkerImageTag = (projectRoot: string): string => {
  const absoluteRoot = resolve(projectRoot);
  const project = basename(absoluteRoot)
    .toLowerCase()
    .replace(/[^a-z0-9_.-]+/gu, "-")
    .replace(/^-+|-+$/gu, "") || "project";
  return `lfi-worker-${project}-${digest(absoluteRoot).slice(0, 12)}`;
};

const agentPackage: Record<AgentProvider, string> = {
  codex: "@openai/codex",
  claude: "@anthropic-ai/claude-code",
  pi: "@mariozechner/pi-coding-agent",
  dsh: "deepseek-harness",
};

export const generateWorkerImageLayer = (
  agents: ReadonlySet<AgentProvider>,
): string => {
  const packages = [...agents].sort().map((agent) => agentPackage[agent]);
  const install = packages.length > 0
    ? `RUN npm install --global ${packages.join(" ")}\n`
    : "";
  return `
# This layer is generated by LFI. Do not copy it into the project or edit it.
ARG LFI_UID
ARG LFI_GID
RUN groupadd --non-unique --gid "\${LFI_GID}" lfi-agent \\
 && useradd --non-unique --uid "\${LFI_UID}" --gid "\${LFI_GID}" --create-home lfi-agent
${install}RUN printf '%s\\n' '#!/bin/sh' 'exec "$@"' > /usr/local/bin/lfi-worker-entrypoint \\
 && chmod 0755 /usr/local/bin/lfi-worker-entrypoint
USER \${LFI_UID}:\${LFI_GID}
ENTRYPOINT ["/usr/local/bin/lfi-worker-entrypoint"]
`;
};

export const workerDockerfileScaffold = (): string => `# This Dockerfile belongs to your project. Commit and edit it freely.
# Этот Dockerfile принадлежит проекту: коммитьте и редактируйте его свободно.
# Add the language runtimes, system libraries, and tools your validation needs.
# Добавьте среды языков, системные библиотеки и инструменты для проверки проекта.
# It must end as root so LFI can add the agent user in its generated layer.
# Последним пользователем должен быть root, чтобы LFI мог добавить пользователя агента.
# Agent CLI tooling is supplied by LFI; do not install it here.
# LFI добавляет CLI агентов сам; не устанавливайте их здесь.
FROM node:22

USER root
`;

export const scaffoldWorkerDockerfile = async (projectRoot: string): Promise<void> => {
  try {
    await writeFile(join(projectRoot, WORKER_DOCKERFILE), workerDockerfileScaffold(), {
      flag: "wx",
    });
  } catch (error) {
    if (
      typeof error === "object" &&
      error !== null &&
      "code" in error &&
      error.code === "EEXIST"
    ) return;
    throw error;
  }
};

const currentIdentity = (): WorkerIdentity => {
  if (process.getuid === undefined || process.getgid === undefined) {
    throw new Error(
      "Worker images require a numeric user identity / Для образа worker нужен числовой идентификатор пользователя.",
    );
  }
  return { uid: process.getuid(), gid: process.getgid() };
};

interface WorkerImageOptions {
  projectRoot: string;
  identity?: WorkerIdentity;
  version?: string;
  runtime?: string;
  env?: NodeJS.ProcessEnv;
}

interface WorkerImageInputs {
  identity: WorkerIdentity;
  version: string;
  userLayer: string;
}

const readWorkerImageInputs = async (
  options: WorkerImageOptions,
): Promise<WorkerImageInputs> => ({
  identity: options.identity ?? currentIdentity(),
  version: options.version ?? LFI_VERSION,
  userLayer: await readFile(join(options.projectRoot, WORKER_DOCKERFILE), "utf8"),
});

export const buildWorkerImage = async (
  options: WorkerImageOptions & { config: LfiConfig },
): Promise<void> => {
  const { identity, version, userLayer } = await readWorkerImageInputs(options);
  const source = `${userLayer.replace(/\s*$/u, "\n")}${generateWorkerImageLayer(configuredAgents(options.config))}`;
  const metadata = `LABEL ${labels.dockerfile}="${digest(userLayer)}"\nLABEL ${labels.version}="${version}"\nLABEL ${labels.uid}="${identity.uid}"\nLABEL ${labels.gid}="${identity.gid}"\n`;
  await requireCommand(
    options.runtime ?? "docker",
    [
      "build",
      "--tag",
      deriveWorkerImageTag(options.projectRoot),
      "--build-arg",
      `LFI_UID=${identity.uid}`,
      "--build-arg",
      `LFI_GID=${identity.gid}`,
      "--file",
      "-",
      options.projectRoot,
    ],
    {
      cwd: options.projectRoot,
      input: `${source}${metadata}`,
      ...(options.env ? { env: options.env } : {}),
    },
  );
};

const stringRecord = (value: unknown): Record<string, string> | undefined => {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return undefined;
  const entries = Object.entries(value);
  if (!entries.every((entry) => typeof entry[1] === "string")) return undefined;
  return Object.fromEntries(entries);
};

export const checkWorkerImageFreshness = async (
  options: WorkerImageOptions,
): Promise<WorkerImageFreshness> => {
  const { identity, version, userLayer } = await readWorkerImageInputs(options);
  const result = await runCommand(
    options.runtime ?? "docker",
    [
      "image",
      "inspect",
      deriveWorkerImageTag(options.projectRoot),
      "--format",
      "{{json .Config.Labels}}",
    ],
    { cwd: options.projectRoot, ...(options.env ? { env: options.env } : {}) },
  );
  if (result.exitCode !== 0) return { status: "missing" };
  let imageLabels: Record<string, string> | undefined;
  try {
    imageLabels = stringRecord(JSON.parse(result.stdout));
  } catch {
    imageLabels = undefined;
  }
  const reasons: ("dockerfile" | "version" | "identity")[] = [];
  if (imageLabels?.[labels.dockerfile] !== digest(userLayer)) reasons.push("dockerfile");
  if (imageLabels?.[labels.version] !== version) reasons.push("version");
  if (
    imageLabels?.[labels.uid] !== String(identity.uid) ||
    imageLabels?.[labels.gid] !== String(identity.gid)
  ) reasons.push("identity");
  return reasons.length > 0 ? { status: "stale", reasons } : { status: "fresh" };
};
